# Generated by Django 4.2.20 on 2025-10-01 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="部门名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="部门描述"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
            ],
            options={
                "verbose_name": "部门",
                "verbose_name_plural": "部门管理",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(max_length=20, unique=True, verbose_name="员工工号"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "gender",
                    models.BooleanField(
                        choices=[(True, "男"), (False, "女")], verbose_name="性别"
                    ),
                ),
                ("birthday", models.DateField(verbose_name="出生日期")),
                (
                    "id_card",
                    models.CharField(max_length=18, unique=True, verbose_name="身份证号"),
                ),
                ("phone", models.CharField(max_length=11, verbose_name="手机号码")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                ("entry_date", models.DateField(verbose_name="入职日期")),
                (
                    "job_status",
                    models.CharField(
                        choices=[
                            ("probation", "试用期"),
                            ("regular", "正式"),
                            ("resigned", "已离职"),
                        ],
                        default="probation",
                        max_length=20,
                        verbose_name="工作状态",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="住址"
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="紧急联系人"
                    ),
                ),
                (
                    "emergency_phone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="紧急联系电话"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="头像"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "leave_date",
                    models.DateField(blank=True, null=True, verbose_name="离职日期"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="personnel.department",
                        verbose_name="所属部门",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工",
                "verbose_name_plural": "员工管理",
                "ordering": ["-entry_date"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="职位名称")),
                ("level", models.IntegerField(default=1, verbose_name="职位级别")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="职位描述"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "职位",
                "verbose_name_plural": "职位管理",
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100, verbose_name="公司名称")),
                ("position", models.CharField(max_length=100, verbose_name="职位")),
                ("start_date", models.DateField(verbose_name="开始时间")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="工作描述"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experiences",
                        to="personnel.employee",
                        verbose_name="员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作经历",
                "verbose_name_plural": "工作经历管理",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "education_background",
                    models.CharField(
                        choices=[
                            ("high_school", "高中"),
                            ("college", "专科"),
                            ("bachelor", "本科"),
                            ("master", "硕士"),
                            ("doctor", "博士"),
                        ],
                        max_length=50,
                        verbose_name="学历",
                    ),
                ),
                (
                    "major",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="专业"
                    ),
                ),
                (
                    "graduate_school",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="毕业院校"
                    ),
                ),
                (
                    "graduate_date",
                    models.DateField(blank=True, null=True, verbose_name="毕业日期"),
                ),
                (
                    "political_status",
                    models.CharField(
                        choices=[
                            ("communist", "中共党员"),
                            ("league_member", "共青团员"),
                            ("democrat", "民主党派"),
                            ("mass", "群众"),
                        ],
                        default="mass",
                        max_length=20,
                        verbose_name="政治面貌",
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="银行卡号"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="银行名称"
                    ),
                ),
                (
                    "social_insurance_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="社保号"
                    ),
                ),
                (
                    "medical_insurance_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="医保号"
                    ),
                ),
                (
                    "housing_fund_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="公积金号"
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="personnel.employee",
                        verbose_name="员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工档案",
                "verbose_name_plural": "员工档案管理",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="personnel.position",
                verbose_name="职位",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.CreateModel(
            name="EducationExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=100, verbose_name="学校名称")),
                ("major", models.CharField(max_length=100, verbose_name="专业")),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("high_school", "高中"),
                            ("college", "专科"),
                            ("bachelor", "本科"),
                            ("master", "硕士"),
                            ("doctor", "博士"),
                        ],
                        max_length=50,
                        verbose_name="学历",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始时间")),
                ("end_date", models.DateField(verbose_name="结束时间")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_experiences",
                        to="personnel.employee",
                        verbose_name="员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "教育经历",
                "verbose_name_plural": "教育经历管理",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_departments",
                to="personnel.employee",
                verbose_name="部门经理",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="parent_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_departments",
                to="personnel.department",
                verbose_name="上级部门",
            ),
        ),
    ]
