# Generated by Django 4.2.20 on 2025-10-01 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("personnel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女")],
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
                ("phone_number", models.CharField(max_length=20, verbose_name="手机号码")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="电子邮箱"
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="学历"
                    ),
                ),
                (
                    "work_experience",
                    models.IntegerField(default=0, verbose_name="工作经验(年)"),
                ),
                (
                    "expected_salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="期望薪资下限",
                    ),
                ),
                (
                    "expected_salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="期望薪资上限",
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True, null=True, upload_to="resumes/", verbose_name="简历"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("screening", "筛选中"),
                            ("interviewing", "面试中"),
                            ("pass", "通过"),
                            ("reject", "拒绝"),
                            ("offer", "已发offer"),
                            ("employed", "已入职"),
                            ("abandoned", "已放弃"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("summary", models.TextField(blank=True, null=True, verbose_name="总结")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "应聘者",
                "verbose_name_plural": "应聘者管理",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="渠道名称"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "招聘渠道",
                "verbose_name_plural": "招聘渠道管理",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField(verbose_name="统计期间")),
                (
                    "period_type",
                    models.CharField(
                        choices=[("month", "月度"), ("quarter", "季度"), ("year", "年度")],
                        default="month",
                        max_length=20,
                        verbose_name="统计周期类型",
                    ),
                ),
                (
                    "total_candidates",
                    models.IntegerField(default=0, verbose_name="应聘者总数"),
                ),
                (
                    "interviewed_candidates",
                    models.IntegerField(default=0, verbose_name="面试人数"),
                ),
                (
                    "passed_candidates",
                    models.IntegerField(default=0, verbose_name="通过人数"),
                ),
                (
                    "offer_candidates",
                    models.IntegerField(default=0, verbose_name="发放Offer人数"),
                ),
                (
                    "accepted_offer_candidates",
                    models.IntegerField(default=0, verbose_name="接受Offer人数"),
                ),
                (
                    "onboarding_candidates",
                    models.IntegerField(default=0, verbose_name="实际入职人数"),
                ),
                (
                    "recruitment_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="招聘成本"
                    ),
                ),
                (
                    "average_recruitment_time",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="平均招聘周期(天)"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "招聘统计",
                "verbose_name_plural": "招聘统计管理",
                "ordering": ["-period"],
                "unique_together": {("period", "period_type")},
            },
        ),
        migrations.CreateModel(
            name="RecruitmentRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_of_recruits",
                    models.IntegerField(default=1, verbose_name="招聘人数"),
                ),
                (
                    "urgent_level",
                    models.CharField(
                        choices=[
                            ("normal", "普通"),
                            ("urgent", "紧急"),
                            ("very_urgent", "非常紧急"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="紧急程度",
                    ),
                ),
                (
                    "expected_salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="期望薪资下限",
                    ),
                ),
                (
                    "expected_salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="期望薪资上限",
                    ),
                ),
                (
                    "work_experience_min",
                    models.IntegerField(default=0, verbose_name="最低工作经验(年)"),
                ),
                (
                    "work_experience_max",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="最高工作经验(年)"
                    ),
                ),
                (
                    "education_requirement",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="学历要求"
                    ),
                ),
                ("job_description", models.TextField(verbose_name="岗位职责")),
                ("qualification_requirements", models.TextField(verbose_name="任职要求")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("submitted", "已提交"),
                            ("approved", "已批准"),
                            ("rejected", "已拒绝"),
                            ("closed", "已关闭"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "approval_comment",
                    models.TextField(blank=True, null=True, verbose_name="审批意见"),
                ),
                (
                    "approval_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="审批时间"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_requirements",
                        to="personnel.department",
                        verbose_name="需求部门",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_requirements",
                        to="personnel.position",
                        verbose_name="职位",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recruitment_requirements",
                        to="personnel.employee",
                        verbose_name="招聘负责人",
                    ),
                ),
            ],
            options={
                "verbose_name": "招聘需求",
                "verbose_name_plural": "招聘需求管理",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actual_start_date",
                    models.DateField(blank=True, null=True, verbose_name="实际入职日期"),
                ),
                (
                    "id_card_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="身份证号"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="居住地址"
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="紧急联系人姓名"
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="紧急联系人电话"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="银行卡所属银行"
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="银行账号"
                    ),
                ),
                (
                    "documents_status",
                    models.CharField(
                        choices=[
                            ("pending", "待提交"),
                            ("complete", "已提交"),
                            ("verified", "已审核"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="证件材料状态",
                    ),
                ),
                (
                    "orientation_completed",
                    models.BooleanField(default=False, verbose_name="入职培训完成"),
                ),
                (
                    "onboarding_status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("canceled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="入职状态",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_info",
                        to="recruitment.candidate",
                        verbose_name="应聘者",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarding_info",
                        to="personnel.employee",
                        verbose_name="员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "入职信息",
                "verbose_name_plural": "入职信息管理",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="月薪"
                    ),
                ),
                (
                    "annual_bonus",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="年终奖",
                    ),
                ),
                (
                    "benefits",
                    models.TextField(blank=True, null=True, verbose_name="福利待遇"),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="入职日期"),
                ),
                (
                    "probation_period",
                    models.IntegerField(default=3, verbose_name="试用期(月)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("sent", "已发送"),
                            ("accepted", "已接受"),
                            ("rejected", "已拒绝"),
                            ("expired", "已过期"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "send_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="发送时间"),
                ),
                (
                    "accept_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="接受时间"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer",
                        to="recruitment.candidate",
                        verbose_name="应聘者",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="personnel.department",
                        verbose_name="部门",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="personnel.position",
                        verbose_name="职位",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_offers",
                        to="personnel.employee",
                        verbose_name="发送人",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer",
                "verbose_name_plural": "Offer管理",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("phone", "电话面试"),
                            ("first", "一面"),
                            ("second", "二面"),
                            ("final", "终面"),
                        ],
                        max_length=50,
                        verbose_name="面试类型",
                    ),
                ),
                (
                    "interview_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="面试时间"),
                ),
                (
                    "interview_location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="面试地点"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待安排"),
                            ("scheduled", "已安排"),
                            ("completed", "已完成"),
                            ("canceled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(blank=True, null=True, verbose_name="面试得分"),
                ),
                (
                    "conclusion",
                    models.TextField(blank=True, null=True, verbose_name="面试结论"),
                ),
                (
                    "suggestion",
                    models.TextField(blank=True, null=True, verbose_name="建议"),
                ),
                (
                    "next_step",
                    models.TextField(blank=True, null=True, verbose_name="下一步安排"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="recruitment.candidate",
                        verbose_name="应聘者",
                    ),
                ),
                (
                    "interviewers",
                    models.ManyToManyField(
                        related_name="interviews",
                        to="personnel.employee",
                        verbose_name="面试官",
                    ),
                ),
            ],
            options={
                "verbose_name": "面试记录",
                "verbose_name_plural": "面试记录管理",
                "ordering": ["-interview_time"],
            },
        ),
        migrations.AddField(
            model_name="candidate",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="recruitment.recruitmentchannel",
                verbose_name="招聘渠道",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="recruiter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="personnel.employee",
                verbose_name="招聘负责人",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="recruitment_requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="recruitment.recruitmentrequirement",
                verbose_name="招聘需求",
            ),
        ),
    ]
