# Generated by Django 5.2.9 on 2025-12-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('screening', '筛选中'), ('interviewing', '面试中'), ('pass', '通过'), ('reject', '拒绝'), ('offer', '已发offer'), ('employed', '已入职'), ('abandoned', '已放弃')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='work_experience',
            field=models.IntegerField(db_index=True, default=0, verbose_name='工作经验(年)'),
        ),
    ]
