# Generated by Django 4.2.20 on 2025-10-01 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("personnel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppraisalPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="计划名称")),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                ("due_date", models.DateField(verbose_name="截止日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("scheduled", "已计划"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("closed", "已关闭"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="计划描述"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "考核计划",
                "verbose_name_plural": "考核计划管理",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="AppraisalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="考核周期开始日期")),
                ("end_date", models.DateField(verbose_name="考核周期结束日期")),
                (
                    "self_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="自评分数",
                    ),
                ),
                (
                    "appraiser_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="考核人分数",
                    ),
                ),
                (
                    "final_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="最终分数",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="等级"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("self_assessment", "自评中"),
                            ("appraisal", "考核中"),
                            ("review", "审核中"),
                            ("completed", "已完成"),
                            ("rejected", "已驳回"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "self_comment",
                    models.TextField(blank=True, null=True, verbose_name="自评意见"),
                ),
                (
                    "appraiser_comment",
                    models.TextField(blank=True, null=True, verbose_name="考核人意见"),
                ),
                (
                    "review_comment",
                    models.TextField(blank=True, null=True, verbose_name="审核意见"),
                ),
                (
                    "self_assessment_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="自评完成时间"),
                ),
                (
                    "appraisal_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="考核完成时间"),
                ),
                (
                    "review_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核完成时间"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "appraiser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appraised_records",
                        to="personnel.employee",
                        verbose_name="考核人",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appraisal_records",
                        to="personnel.employee",
                        verbose_name="员工",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appraisal_records",
                        to="performance.appraisalplan",
                        verbose_name="考核计划",
                    ),
                ),
            ],
            options={
                "verbose_name": "考核记录",
                "verbose_name_plural": "考核记录管理",
                "ordering": ["-end_date"],
                "unique_together": {("employee", "plan")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceAppraisalType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="考核类型名称"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="考核类型编码"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "月度"),
                            ("quarterly", "季度"),
                            ("semiannually", "半年"),
                            ("annually", "年度"),
                        ],
                        max_length=20,
                        verbose_name="考核频率",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "绩效考核类型",
                "verbose_name_plural": "绩效考核类型管理",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="等级名称"),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="等级编码"),
                ),
                (
                    "min_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="最低分数"
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="最高分数"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="等级描述"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="代表颜色"
                    ),
                ),
            ],
            options={
                "verbose_name": "绩效等级",
                "verbose_name_plural": "绩效等级管理",
                "ordering": ["min_score"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="指标名称")),
                ("code", models.CharField(max_length=20, verbose_name="指标编码")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="指标描述"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="权重(%)"
                    ),
                ),
                (
                    "indicator_type",
                    models.CharField(
                        choices=[("quantitative", "定量"), ("qualitative", "定性")],
                        max_length=20,
                        verbose_name="指标类型",
                    ),
                ),
                (
                    "measurement_method",
                    models.TextField(blank=True, null=True, verbose_name="测量方法"),
                ),
                ("target", models.TextField(blank=True, null=True, verbose_name="目标值")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "绩效考核指标",
                "verbose_name_plural": "绩效考核指标管理",
                "ordering": ["code"],
                "unique_together": {("code", "name")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="模板描述"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认模板"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_templates",
                        to="personnel.department",
                        verbose_name="适用部门",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_templates",
                        to="personnel.position",
                        verbose_name="适用岗位",
                    ),
                ),
            ],
            options={
                "verbose_name": "绩效考核模板",
                "verbose_name_plural": "绩效考核模板管理",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="反馈内容")),
                (
                    "improvement_suggestions",
                    models.TextField(blank=True, null=True, verbose_name="改进建议"),
                ),
                ("is_private", models.BooleanField(default=False, verbose_name="是否私密")),
                (
                    "feedback_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="反馈时间"),
                ),
                (
                    "appraisal_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="performance.appraisalrecord",
                        verbose_name="考核记录",
                    ),
                ),
                (
                    "feedback_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provided_feedbacks",
                        to="personnel.employee",
                        verbose_name="反馈提供者",
                    ),
                ),
            ],
            options={
                "verbose_name": "绩效反馈",
                "verbose_name_plural": "绩效反馈管理",
                "ordering": ["-feedback_time"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceAppeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="申诉原因")),
                (
                    "evidence",
                    models.TextField(blank=True, null=True, verbose_name="证据说明"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("reviewing", "审核中"),
                            ("accepted", "已受理"),
                            ("rejected", "已驳回"),
                            ("closed", "已关闭"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "review_comment",
                    models.TextField(blank=True, null=True, verbose_name="审核意见"),
                ),
                (
                    "appeal_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="申诉时间"),
                ),
                (
                    "review_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "appraisal_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appeal",
                        to="performance.appraisalrecord",
                        verbose_name="考核记录",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_appeals",
                        to="personnel.employee",
                        verbose_name="审核人",
                    ),
                ),
            ],
            options={
                "verbose_name": "绩效申诉",
                "verbose_name_plural": "绩效申诉管理",
                "ordering": ["-appeal_time"],
            },
        ),
        migrations.AddField(
            model_name="appraisalplan",
            name="appraisal_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appraisal_plans",
                to="performance.performanceappraisaltype",
                verbose_name="考核类型",
            ),
        ),
        migrations.AddField(
            model_name="appraisalplan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_appraisal_plans",
                to="personnel.employee",
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="appraisalplan",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appraisal_plans",
                to="personnel.department",
                verbose_name="考核部门",
            ),
        ),
        migrations.AddField(
            model_name="appraisalplan",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appraisal_plans",
                to="performance.performancetemplate",
                verbose_name="考核模板",
            ),
        ),
        migrations.CreateModel(
            name="TemplateIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="权重(%)"
                    ),
                ),
                ("target", models.TextField(blank=True, null=True, verbose_name="目标值")),
                (
                    "measurement_method",
                    models.TextField(blank=True, null=True, verbose_name="测量方法"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_indicators",
                        to="performance.performanceindicator",
                        verbose_name="考核指标",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="performance.performancetemplate",
                        verbose_name="考核模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "模板指标",
                "verbose_name_plural": "模板指标管理",
                "ordering": ["sort_order"],
                "unique_together": {("template", "indicator")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField(verbose_name="统计期间")),
                (
                    "period_type",
                    models.CharField(
                        choices=[("month", "月度"), ("quarter", "季度"), ("year", "年度")],
                        default="month",
                        max_length=20,
                        verbose_name="统计周期类型",
                    ),
                ),
                (
                    "total_employees",
                    models.IntegerField(default=0, verbose_name="考核员工总数"),
                ),
                (
                    "average_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="平均分数",
                    ),
                ),
                (
                    "grade_distribution",
                    models.JSONField(blank=True, null=True, verbose_name="等级分布"),
                ),
                (
                    "improvement_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="进步率(%)",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_statistics",
                        to="personnel.department",
                        verbose_name="部门",
                    ),
                ),
            ],
            options={
                "verbose_name": "绩效统计",
                "verbose_name_plural": "绩效统计管理",
                "ordering": ["-period"],
                "unique_together": {("period", "period_type", "department")},
            },
        ),
        migrations.CreateModel(
            name="IndicatorScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "self_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="自评分数",
                    ),
                ),
                (
                    "appraiser_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="考核人分数",
                    ),
                ),
                (
                    "final_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="最终分数",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="权重(%)"
                    ),
                ),
                (
                    "self_comment",
                    models.TextField(blank=True, null=True, verbose_name="自评说明"),
                ),
                (
                    "appraiser_comment",
                    models.TextField(blank=True, null=True, verbose_name="考核人说明"),
                ),
                (
                    "appraisal_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator_scores",
                        to="performance.appraisalrecord",
                        verbose_name="考核记录",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator_scores",
                        to="performance.performanceindicator",
                        verbose_name="考核指标",
                    ),
                ),
            ],
            options={
                "verbose_name": "指标评分",
                "verbose_name_plural": "指标评分管理",
                "unique_together": {("appraisal_record", "indicator")},
            },
        ),
    ]
