# Generated by Django 4.2.20 on 2025-10-01 02:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("personnel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryItemType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="薪资项类型名称"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="薪资项类型编码"
                    ),
                ),
                ("is_taxable", models.BooleanField(default=True, verbose_name="是否应税")),
                ("is_benefit", models.BooleanField(default=False, verbose_name="是否福利")),
                (
                    "is_deduction",
                    models.BooleanField(default=False, verbose_name="是否扣除项"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
            ],
            options={
                "verbose_name": "薪资项类型",
                "verbose_name_plural": "薪资项类型管理",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="SalaryPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_month", models.DateField(verbose_name="发放月份")),
                (
                    "payment_date",
                    models.DateField(blank=True, null=True, verbose_name="发放日期"),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="基本工资"
                    ),
                ),
                (
                    "position_salary",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="岗位工资"
                    ),
                ),
                (
                    "performance_salary",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="绩效工资"
                    ),
                ),
                (
                    "bonus",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="奖金"
                    ),
                ),
                (
                    "allowance_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="津贴补贴合计",
                    ),
                ),
                (
                    "other_income_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="其他收入合计",
                    ),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="应发工资"
                    ),
                ),
                (
                    "social_insurance_deduction",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="社保扣除"
                    ),
                ),
                (
                    "medical_insurance_deduction",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="医保扣除"
                    ),
                ),
                (
                    "housing_fund_deduction",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="公积金扣除"
                    ),
                ),
                (
                    "tax_deduction",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="个税扣除"
                    ),
                ),
                (
                    "other_deduction_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="其他扣除合计",
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="实发工资"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="银行名称"
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="银行账号"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("calculated", "已计算"),
                            ("confirmed", "已确认"),
                            ("paid", "已发放"),
                            ("canceled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "confirm_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="确认时间"),
                ),
                (
                    "payment_status",
                    models.BooleanField(default=False, verbose_name="是否已付款"),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "calculator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculated_salaries",
                        to="personnel.employee",
                        verbose_name="计算人",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_payments",
                        to="personnel.employee",
                        verbose_name="员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "薪资发放记录",
                "verbose_name_plural": "薪资发放记录管理",
                "ordering": ["-payment_month"],
                "unique_together": {("employee", "payment_month")},
            },
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="薪资结构名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认结构"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "薪资结构",
                "verbose_name_plural": "薪资结构管理",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="SalaryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="薪资项名称"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="薪资项编码"),
                ),
                (
                    "default_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="默认金额"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_items",
                        to="salary.salaryitemtype",
                        verbose_name="薪资项类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "薪资项",
                "verbose_name_plural": "薪资项管理",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeSalaryConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="基本工资"
                    ),
                ),
                (
                    "position_salary",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="岗位工资"
                    ),
                ),
                (
                    "performance_salary",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="绩效工资"
                    ),
                ),
                (
                    "bonus",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="奖金"
                    ),
                ),
                (
                    "social_insurance_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="社保基数",
                    ),
                ),
                (
                    "medical_insurance_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="医保基数",
                    ),
                ),
                (
                    "housing_fund_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="公积金基数",
                    ),
                ),
                (
                    "tax_exemption",
                    models.DecimalField(
                        decimal_places=2,
                        default=5000,
                        max_digits=10,
                        verbose_name="个税起征点",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="生效日期"
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_config",
                        to="personnel.employee",
                        verbose_name="员工",
                    ),
                ),
                (
                    "salary_structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_configs",
                        to="salary.salarystructure",
                        verbose_name="薪资结构",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工薪资配置",
                "verbose_name_plural": "员工薪资配置管理",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="SalaryStructureDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="金额"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "formula",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="计算公式"
                    ),
                ),
                ("is_fixed", models.BooleanField(default=False, verbose_name="是否固定金额")),
                (
                    "salary_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structure_details",
                        to="salary.salaryitem",
                        verbose_name="薪资项",
                    ),
                ),
                (
                    "salary_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="salary.salarystructure",
                        verbose_name="薪资结构",
                    ),
                ),
            ],
            options={
                "verbose_name": "薪资结构详情",
                "verbose_name_plural": "薪资结构详情管理",
                "ordering": ["sort_order"],
                "unique_together": {("salary_structure", "salary_item")},
            },
        ),
        migrations.CreateModel(
            name="SalaryPaymentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="金额"
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "salary_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_details",
                        to="salary.salaryitem",
                        verbose_name="薪资项",
                    ),
                ),
                (
                    "salary_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="salary.salarypayment",
                        verbose_name="薪资发放记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "薪资发放详情",
                "verbose_name_plural": "薪资发放详情管理",
                "unique_together": {("salary_payment", "salary_item")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeSalaryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="金额"
                    ),
                ),
                ("is_fixed", models.BooleanField(default=False, verbose_name="是否固定")),
                (
                    "effective_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="生效日期"
                    ),
                ),
                (
                    "employee_salary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_items",
                        to="salary.employeesalaryconfig",
                        verbose_name="员工薪资配置",
                    ),
                ),
                (
                    "salary_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_items",
                        to="salary.salaryitem",
                        verbose_name="薪资项",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工薪资项",
                "verbose_name_plural": "员工薪资项管理",
                "unique_together": {("employee_salary", "salary_item")},
            },
        ),
    ]
