"""
Django settings for code_agent project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-bp4gtjan_m7fz#c#+of1qp03vlef$j^cmch362z8$xv(@05^4_"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'simpleui',  # 将simpleui加入到INSTALLED_APPS里去，放在第一行
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # app
    'attendance',
    'performance',
    'personnel',
    'recruitment',
    'salary',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "company_management.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "company_management.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # MySQL 引擎
        'NAME': 'company_management',                   # 虚拟机中创建的数据库名
        'USER': 'dbproj',                 # 虚拟机 MySQL 远程用户
        'PASSWORD': '2025dbp',          # 用户密码
        'HOST': '192.168.245.129',             # 虚拟机 IP
        'PORT': '3306',                        # MySQL 端口
        'OPTIONS': {
            'charset': 'utf8mb4',              # 支持中文和表情
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        # 无密码格式：redis://虚拟机IP:端口/数据库编号
        "LOCATION": "redis://192.168.245.129:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# 会话存储配置（保留）
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'  # 设置语言为简体中文 [^54^]
TIME_ZONE = 'Asia/Shanghai'  # 设置时区为上海 [^54^]

# 启用国际化
USE_I18N = True
USE_L10N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# 静态文件配置
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 去掉默认Logo或换成自己Logo链接
SIMPLEUI_LOGO = '/static/img/logo.png'

# 隐藏右侧SimpleUI广告链接和使用分析
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

# 设置默认主题，指向主题css文件名。你可以选择以下主题之一：
# 'admin.lte.css'  # Admin Lte风格
# 'element.css'    # Element-ui风格
# 'layui.css'      # layui风格
# 'purple.css'     # 紫色风格
SIMPLEUI_DEFAULT_THEME = 'element.css'

# 隐藏首页的快捷操作和最近动作
SIMPLEUI_HOME = True  # 隐藏默认的首页菜单
SIMPLEUI_HOME_QUICK = True
SIMPLEUI_HOME_ACTION = True

# SimpleUI菜单配置
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['人事管理', '考勤管理', '薪资管理', '招聘管理', '绩效管理', '系统管理'],
    'dynamic': False,

    'menus': [
        {
            'name': '人事管理',
            'icon': 'fa fa-users',
            'models': [
                {
                    'name': '部门管理',
                    'icon': 'fa fa-building',
                    'url': 'personnel/department/'
                },
                {
                    'name': '职位管理',
                    'icon': 'fa fa-briefcase',
                    'url': 'personnel/position/'
                },
                {
                    'name': '员工管理',
                    'icon': 'fa fa-user',
                    'url': 'personnel/employee/'
                },
            ]
        },
        {
            'name': '考勤管理',
            'icon': 'fa fa-calendar-check',
            'models': [
                {
                    'name': '考勤记录',
                    'icon': 'fa fa-clock',
                    'url': 'attendance/attendancerecord/'
                },
                {
                    'name': '请假类型',
                    'icon': 'fa fa-calendar-plus',
                    'url': 'attendance/leavetype/'
                },
                {
                    'name': '请假申请',
                    'icon': 'fa fa-calendar-minus',
                    'url': 'attendance/leaverequest/'
                },
                {
                    'name': '加班类型',
                    'icon': 'fa fa-bolt',
                    'url': 'attendance/overtimetype/'
                },
                {
                    'name': '加班申请',
                    'icon': 'fa fa-plus-square',
                    'url': 'attendance/overtimerequest/'
                },
                {
                    'name': '考勤汇总',
                    'icon': 'fa fa-bar-chart',
                    'url': 'attendance/attendancesummary/'
                },
            ]
        },
        {
            'name': '薪资管理',
            'icon': 'fa fa-list-alt',
            'models': [
                {
                    'name': '薪资项类型',
                    'icon': 'fa fa-list-ul',
                    'url': 'salary/salaryitemtype/'
                },
                {
                    'name': '薪资项',
                    'icon': 'fa fa-list-alt',
                    'url': 'salary/salaryitem/'
                },
                {
                    'name': '薪资结构',
                    'icon': 'fa fa-sitemap',
                    'url': 'salary/salarystructure/'
                },
                {
                    'name': '员工薪资配置',
                    'icon': 'fa fa-cog',
                    'url': 'salary/employeesalaryconfig/'
                },
                {
                    'name': '薪资发放记录',
                    'icon': 'fa fa-credit-card',
                    'url': 'salary/salarypayment/'
                },
            ]
        },
        {
            'name': '招聘管理',
            'icon': 'fa fa-handshake',
            'models': [
                {
                    'name': '招聘渠道',
                    'icon': 'fa fa-link',
                    'url': 'recruitment/recruitmentchannel/'
                },
                {
                    'name': '招聘需求',
                    'icon': 'fa fa-file-text',
                    'url': 'recruitment/recruitmentrequirement/'
                },
                {
                    'name': '应聘者管理',
                    'icon': 'fa fa-user-plus',
                    'url': 'recruitment/candidate/'
                },
                {
                    'name': '面试记录',
                    'icon': 'fa fa-comments',
                    'url': 'recruitment/interview/'
                },
                {
                    'name': '录用通知',
                    'icon': 'fa fa-envelope',
                    'url': 'recruitment/offer/'
                },
                {
                    'name': '入职信息',
                    'icon': 'fa fa-pie-chart',
                    'url': 'recruitment/onboardinginfo/'
                },
            ]
        },
        {
            'name': '绩效管理',
            'icon': 'fa fa-trophy',
            'models': [
                {
                    'name': '考核类型',
                    'icon': 'fa fa-list-ol',
                    'url': 'performance/performanceappraisaltype/'
                },
                {
                    'name': '考核指标',
                    'icon': 'fa fa-bullseye',
                    'url': 'performance/performanceindicator/'
                },
                {
                    'name': '考核模板',
                    'icon': 'fa fa-file-text',
                    'url': 'performance/performancetemplate/'
                },
                {
                    'name': '考核计划',
                    'icon': 'fa fa-calendar',
                    'url': 'performance/appraisalplan/'
                },
                {
                    'name': '考核记录',
                    'icon': 'fa fa-file',
                    'url': 'performance/appraisalrecord/'
                },
                {
                    'name': '绩效等级',
                    'icon': 'fa fa-star',
                    'url': 'performance/performancegrade/'
                },
                {
                    'name': '绩效反馈',
                    'icon': 'fa fa-comment',
                    'url': 'performance/performancefeedback/'
                },
                {
                    'name': '绩效申诉',
                    'icon': 'fa fa-gavel',
                    'url': 'performance/performanceappeal/'
                },
            ]
        },
        {
            'name': '系统管理',
            'icon': 'fa fa-cogs',
            'models': [
                {
                    'name': '用户管理',
                    'icon': 'fa fa-user-circle',
                    'url': 'auth/user/'
                },
                {
                    'name': '权限组',
                    'icon': 'fa fa-users',
                    'url': 'auth/group/'
                },
            ]
        }
    ]
}


SIMPLEUI_HOME_PAGE = '/home/'  # 指定自定义首页的URL
SIMPLEUI_HOME_TITLE = '总览'

OPENROUTER_API_KEY = "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"